name: Generate Diagram
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install pylint

      - name: Generate Codebase Diagram
        run: pyreverse -o png -p MyCode .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codebase-diagrams
          path: "*.png"
